### ISSUE TITLE
Different status results for console git and JGit

### ISSUE THREAD

**Issue by newffy** [sbt/sbt-git#92]
Hello, In some cases console command `git status` and call `porcelain.status.call.hasUncommittedChanges` (with JGit 3.7 used in sbt-git) returns different results.
I observed it on renaming files (changing character registry in mac os x case insensitive hfs+) and when using symlinks.
These cases influence -SNAPSHOT suffix and I think `git status` is more correct.
I'd suppose to use your `ConsoleGitRunner` for implementing `hasUncommittedChanges` method in `GitReadonlyInterface` (running `git status --porcelain` command)

**Comment by bchazalet** [comment]
You would not want to rely on the console all the time, as in some configurations there might not be a console with git available.

But if `porcelain.status.call.hasUncommittedChanges` is incorrect we should try to find a better way to implement it with other JGit methods.

Could you provide a test, i.e. a list of steps I could repeat on my machine?

**Comment by newffy** [comment]
I'd prefer to rely on console when GitRunner rely on it, i.e. depending on useJGit flag. I suppose that will be more consistent behavior - all of plugin functionality rely on console or on JGit.

Yes, I'll try to provide steps to reproduce at least case with symlink today.

**Comment by newffy** [comment]
```
git init testsymlink
cd ./testsymlink/
mkdir project
mkdir usefulFolder
touch usefulFolder/justFile.txt
touch build.sbt
cd ./project/
ln -s ../usefulFolder ./usefulFolder
cd ..


sbt show gitUncommittedChanges 
-> true

git status
-> nothing new (maybe excepting untracked files. You can add them to .gitignore, but gitUncommittedChanges doesn't count them)
```

**Comment by bchazalet** [comment]
@newffy which version of sbt-git are you using, the latest?

I have tried to reproduce your test (I'm running mac os)

```
> reload
..
> git status
[info] On branch master
[info]
[info] Initial commit
[info]
[info] Untracked files:
[info]   (use "git add <file>..." to include in what will be committed)
[info]
[info] 	build.sbt
[info] 	project/
[info] 	target/
[info] 	usefulFolder/
[info]
[info] nothing added to commit but untracked files present (use "git add" to track)
> show gitUncommittedChanges
[info] false
>
```

but I am not getting gitUncommitedChanges = true. I must have missed something..

**Comment by newffy** [comment]
Oh, I'm sorry. I forget to copy also commands 
```git add .
git commit -a -m "initial commit"```

after that you need to check ```git status``` and ```gitUncommittedChanges```

**Comment by newffy** [comment]
You can check this test repo: https://github.com/newffy/testsymlink

**Comment by bchazalet** [comment]
I think you might have an unwanted symlink in usefolder, I have removed it on my [fork](https://github.com/bchazalet/testsymlink/commit/b8f2faa74270754ecb5f2b78b056d6c5a3a031db).

Anyhow, I see my gitUncommitedChanges set to true now indeed.

**Comment by noorul** [comment]
This is also hitting us. Is there a work around. I am using Mac OSX and also I tested on Linux. I see this on both. But then I use JGit directly on the repo status.call.hasUncommittedChanges returns false.

**Comment by jsuereth** [comment]
@noorul How are you using jgit directly?  This could be some kind of setup flag we need to fix, if it's not a JGit specific bug.

**Comment by noorul** [comment]
@jsuereth https://gist.github.com/noorul/a365391b398b06a74558

**Comment by jalaziz** [comment]
I can also confirm this behavior when a repository has a symlink. Any chance there's a fix in sight?

**Comment by frosforever** [comment]
Bumped into the same issue. Minor investigation points to `diff.getMissing()` in [Status.java](https://github.com/eclipse/jgit/blob/9e5380e7fb797e83b6f6b5754249bea4cae534e7/org.eclipse.jgit/src/org/eclipse/jgit/api/Status.java#L81) returning files that are clearly present and not missing. Not entirely sure why.

This in spite of `git diff-index --quiet --cached HEAD`, `git diff-files --quiet`, `git diff-index --quiet HEAD`, and `git ls-files --exclude-standard --others` all returning no changes.

**Comment by bchazalet** [comment]
Note that upgrading to JGit 4 (using PR #99) fixes the symlink bug for me.

Is anyone experiencing this bug in a situation that is not related to symbolic links?

**Comment by danielnegri** [comment]
Same here: sbt-git-0.8.5

```
$ git diff-index --cached HEAD
$ git diff-index HEAD
$ git diff-files
$ git ls-files --exclude-standard --others
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean


daniel@macbook:~/project (master)$ sbt
[info] Loading project definition from /Users/daniel/project/scala-project
[info] Updating {file:/Users/daniel/project/scala-project/}scala-project-build-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /Users/daniel/project/scala-project
[info] Updating {file:/Users/daniel/project/scala-project/}scala-project-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
Head Commit: 8a1d3f17441bd5081b2fcf46034b0cd50b6d4604
Version: 1.0.12-SNAPSHOT
Tags: List(v1.0.12)
Snapshot: true
Uncommited Changes: true
[info] Set current project to scala-project (in build file:/Users/daniel/project/)
scala-project(master)> show gitUncommittedChanges
[info] scala-project-api/*:gitUncommittedChanges
[info]  true
[info] scala-project-oidc/*:gitUncommittedChanges
[info]  true
[info] scala-project-client/*:gitUncommittedChanges
[info]  true
[info] scala-project-core/*:gitUncommittedChanges
[info]  true
[info] scala-project-server/*:gitUncommittedChanges
[info]  true
[info] migrations/*:gitUncommittedChanges
[info]  true
[info] docs/*:gitUncommittedChanges
[info]  true
[info] scala-project/*:gitUncommittedChanges
[info]  true
scala-project(master)> 
```

**Comment by NicolasRouquette** [comment]
Ditto, sbt-git 0.8.5

This is happening on a linux VM running CentOS7 where we run jenkins CI.
Since we use a "staging" process via SBT, we check that the repo is clean before publishing artifacts to NexusPro. This check has been failing quite a bit this week.

In the example below, this is happening on a repo with git-lfs.

{quote}
imce-magicdraw-exporter-europa-batch(master)> show gitUncommittedChanges
[info] true
imce-magicdraw-exporter-europa-batch(master)> exit
[jenkins@imce-infr-dev-01 workspace]$ git diff-index --cached HEAD
[jenkins@imce-infr-dev-01 workspace]$ git diff-index HEAD
[jenkins@imce-infr-dev-01 workspace]$ git diff-files
[jenkins@imce-infr-dev-01 workspace]$ git ls-files --exclude-standard --others
[jenkins@imce-infr-dev-01 workspace]$ git status
# On branch master
nothing to commit, working directory clean
[jenkins@imce-infr-dev-01 workspace]$ git lfs status
On branch master
Git LFS objects to be pushed to origin/master:


Git LFS objects to be committed:


Git LFS objects not staged for commit:


[jenkins@imce-infr-dev-01 workspace]$ git lfs fsck
Git LFS fsck OK
{quote}

I'll try @frosforever's workaround.

**Comment by dwijnand** [comment]
Upgraded to JGit 4.5 which should fix this.

**Comment by dwijnand** [comment]
See #99

**Comment by tpolecat** [comment]
This is still happening for me btw … a file rename that differs only in case seems to shows up as an uncommitted change in JGit but not in command-line git.

**Comment by bchazalet** [comment]
@tpolecat we're hoping that the new release (which should hopefully happen today) will fix it. 

If that's not the case, tell us and I'll look into it again.
